;;; sekken-server-test.el --- sekken-server のテスト -*- lexical-binding: t -*-

;; SPDX-License-Identifier: MIT
;;; Code:

(require 'ert)
(require 'sekken-server)

(ert-deftest sekken-server/設定からコマンドラインを組み立てる ()
  (let ((sekken-server-program "/opt/sekken")
        (sekken-server-dic "/d/system.dic.zst")
        (sekken-server-model "/d/model.zst")
        (sekken-server-jisyo "/d/SKK-JISYO.L")
        (sekken-server-lm "/d/lm.zst")
        (sekken-server-user-jisyo nil)
        (sekken-server-adapted-lm nil))
    (should (equal (sekken-server--command)
                   '("/opt/sekken" "server"
                     "--dic" "/d/system.dic.zst"
                     "--model" "/d/model.zst"
                     "--jisyo" "/d/SKK-JISYO.L"
                     "--lm" "/d/lm.zst")))))

(ert-deftest sekken-server/言語モデルが無ければ起動前にエラーにする ()
  (let ((sekken-server-program "/opt/sekken")
        (sekken-server-dic "/d/system.dic.zst")
        (sekken-server-model "/d/model.zst")
        (sekken-server-jisyo "/d/SKK-JISYO.L")
        (sekken-server-lm nil))
    (should-error (sekken-server--command) :type 'user-error)))

(ert-deftest sekken-server/ユーザー辞書は既定で付き_nilなら付けない ()
  (let ((sekken-server-program "/opt/sekken")
        (sekken-server-dic "/d/system.dic.zst")
        (sekken-server-model "/d/model.zst")
        (sekken-server-jisyo "/d/SKK-JISYO.L")
        (sekken-server-lm "/d/lm.zst")
        (sekken-server-user-jisyo "~/.config/sekken/user-jisyo")
        (sekken-server-adapted-lm nil))
    (should (equal (last (sekken-server--command) 2)
                   (list "--user-jisyo"
                         (expand-file-name "~/.config/sekken/user-jisyo"))))
    (should (stringp (default-value 'sekken-server-user-jisyo)))))

(ert-deftest sekken-server/学習した言語モデルの保存先は既定で付き_nilなら付けない ()
  (let ((sekken-server-program "/opt/sekken")
        (sekken-server-dic "/d/system.dic.zst")
        (sekken-server-model "/d/model.zst")
        (sekken-server-jisyo "/d/SKK-JISYO.L")
        (sekken-server-lm "/d/lm.zst")
        (sekken-server-user-jisyo nil)
        (sekken-server-adapted-lm "~/.config/sekken/adapted-lm.zst"))
    (should (equal (last (sekken-server--command) 2)
                   (list "--adapted-lm"
                         (expand-file-name "~/.config/sekken/adapted-lm.zst"))))
    (should (stringp (default-value 'sekken-server-adapted-lm)))
    (setq sekken-server-adapted-lm nil)
    (should-not (member "--adapted-lm" (sekken-server--command)))))

(ert-deftest sekken-server/確定した文は区間と一緒に_adapt_に送る ()
  (let ((sekken-server--connection 'connection)
        request-args)
    (cl-letf (((symbol-function 'jsonrpc-running-p) (lambda (_) t))
              ((symbol-function 'jsonrpc-async-request)
               (lambda (&rest args) (setq request-args args) '(1))))
      (sekken-server-adapt [(:kind "convert" :text "ねこ")] "猫"))
    (should (eq (nth 1 request-args) :adapt))
    (should (equal (nth 2 request-args)
                   '(:pieces [(:kind "convert" :text "ねこ")] :sentence "猫")))))

(ert-deftest sekken-server/接続が無ければ学習のためにエンジンを起こさない ()
  (let ((sekken-server--connection nil)
        (started nil))
    (cl-letf (((symbol-function 'sekken-server-connection)
               (lambda () (setq started t) 'connection))
              ((symbol-function 'jsonrpc-async-request)
               (lambda (&rest _) (error "送ってはいけない"))))
      (should-not (sekken-server-adapt [(:kind "convert" :text "ねこ")] "猫")))
    (should-not started)))

(ert-deftest sekken-server/学習の失敗は握りつぶさず理由を残す ()
  (let ((sekken-server--connection 'connection)
        (sekken-server--adapt-error nil)
        (sekken-server--crashes 0))
    (cl-letf (((symbol-function 'jsonrpc-running-p) (lambda (_) t))
              ((symbol-function 'jsonrpc-async-request)
               (lambda (&rest args)
                 (funcall (plist-get (nthcdr 3 args) :error-fn)
                          (list :code sekken-server--load-failed-code
                                :message "failed to load engine"))
                 '(1))))
      (sekken-server-adapt [(:kind "convert" :text "ねこ")] "猫"))
    (should (equal sekken-server--adapt-error "failed to load engine"))
    (should (= sekken-server--crashes 1))))

(ert-deftest sekken-server/学習の送信に失敗してもエラーを投げず理由を残す ()
  ;; 確定の hook から呼ばれるので、投げると hook ごと外されて自動確定が止まる。
  (let ((sekken-server--connection 'connection)
        (sekken-server--adapt-error nil)
        (sekken-server--crashes 0))
    (cl-letf (((symbol-function 'jsonrpc-running-p) (lambda (_) t))
              ((symbol-function 'jsonrpc-async-request)
               (lambda (&rest _) (error "Process sekken not running"))))
      (sekken-server-adapt [(:kind "convert" :text "ねこ")] "猫"))
    (should (equal sekken-server--adapt-error "Process sekken not running"))
    (should (= sekken-server--crashes 0))))

(ert-deftest sekken-server/学習のタイムアウトはプロセスが生きていれば異常終了として数えない ()
  (let ((sekken-server--connection 'connection)
        (sekken-server--adapt-error nil)
        (sekken-server--crashes 0))
    (cl-letf (((symbol-function 'jsonrpc-running-p) (lambda (_) t))
              ((symbol-function 'jsonrpc-async-request)
               (lambda (&rest args)
                 (funcall (plist-get (nthcdr 3 args) :timeout-fn))
                 '(1))))
      (sekken-server-adapt [(:kind "convert" :text "ねこ")] "猫"))
    (should (equal sekken-server--adapt-error "timeout"))
    (should (= sekken-server--crashes 0))))

(ert-deftest sekken-server/登録は読みと語を_register_に送る ()
  (let (request-args)
    (cl-letf (((symbol-function 'sekken-server-connection)
               (lambda () 'connection))
              ((symbol-function 'jsonrpc-request)
               (lambda (&rest args) (setq request-args args) nil)))
      (sekken-server-register "わらし" "藁市"))
    (should (eq (nth 1 request-args) :register))
    (should (equal (nth 2 request-args) '(:yomi "わらし" :surface "藁市")))))

(ert-deftest sekken-server/登録を断られればエンジンの理由を_user-error_にする ()
  (cl-letf (((symbol-function 'sekken-server-connection)
             (lambda () 'connection))
            ((symbol-function 'jsonrpc-request)
             (lambda (&rest _)
               (signal 'jsonrpc-error
                       '("request id=1 failed:"
                         (jsonrpc-error-code . -32002)
                         (jsonrpc-error-message . "surface must not contain slash"))))))
    (let ((err (should-error (sekken-server-register "ねこ" "猫/犬") :type 'user-error)))
      (should (string-match-p "surface must not contain slash" (cadr err))))))

(ert-deftest sekken-server/設定が欠けていればエラーにする ()
  (let ((sekken-server-dic nil))
    (should-error (sekken-server--command) :type 'user-error)))

(ert-deftest sekken-server/stderrはjsonrpcが期待する名前のバッファに繋ぐ ()
  (let ((sekken-server-program "/opt/sekken")
        (sekken-server-dic "/d/system.dic.zst")
        (sekken-server-model "/d/model.zst")
        (sekken-server-jisyo "/d/SKK-JISYO.L")
        (sekken-server-lm "/d/lm.zst")
        process-args)
    (cl-letf (((symbol-function 'make-process)
               (lambda (&rest args) (setq process-args args) 'process)))
      (sekken-server--make-process))
    (should (equal (buffer-name (plist-get process-args :stderr))
                   "*sekken stderr*"))))

(ert-deftest sekken-server/プロセスが死んで失敗したら連続異常終了として数える ()
  (require 'cl-lib)
  (let ((sekken-server--connection nil)
        (sekken-server--crashes 0))
    (cl-letf (((symbol-function 'sekken-server-connection)
               (lambda () (setq sekken-server--connection nil) 'dead))
              ((symbol-function 'jsonrpc-request)
               (lambda (&rest _) (signal 'jsonrpc-error '("dead")))))
      (should-error (sekken-server-henkan [(:kind "convert" :text "ねこ")] 3))
      (should (= sekken-server--crashes 1)))))

(ert-deftest sekken-server/読み込み失敗の応答はプロセスが生きていても異常終了として数える ()
  (let ((sekken-server--connection 'connection)
        (sekken-server--crashes 0))
    (cl-letf (((symbol-function 'sekken-server-connection)
               (lambda () 'connection))
              ((symbol-function 'jsonrpc-running-p)
               (lambda (_) t))
              ((symbol-function 'jsonrpc-request)
               (lambda (&rest _)
                 (signal 'jsonrpc-error
                         `("request id=1 failed:"
                           (jsonrpc-error-code . ,sekken-server--load-failed-code)
                           (jsonrpc-error-message . "failed to load engine"))))))
      (should-error (sekken-server-henkan [(:kind "convert" :text "ねこ")] 3) :type 'jsonrpc-error)
      (should (= sekken-server--crashes 1)))))

(ert-deftest sekken-server/プロセスが生きていればタイムアウトは異常終了として数えない ()
  (let ((sekken-server--connection 'connection)
        (sekken-server--crashes 0))
    (cl-letf (((symbol-function 'sekken-server-connection)
               (lambda () 'connection))
              ((symbol-function 'jsonrpc-running-p)
               (lambda (_) t))
              ((symbol-function 'jsonrpc-request)
               (lambda (&rest _)
                 (signal 'jsonrpc-error
                         '("request id=1 failed:"
                           (jsonrpc-error-message . "Timed out"))))))
      (should-error (sekken-server-henkan [(:kind "convert" :text "ねこ")] 3) :type 'jsonrpc-error)
      (should (= sekken-server--crashes 0)))))

(ert-deftest sekken-server/起動中の変換は起動用のタイムアウトで待つ ()
  (let ((sekken-server--connection 'connection)
        (sekken-server--warmed nil)
        (sekken-server-timeout 5)
        (sekken-server-startup-timeout 60)
        request-args)
    (cl-letf (((symbol-function 'sekken-server-connection)
               (lambda () 'connection))
              ((symbol-function 'jsonrpc-request)
               (lambda (&rest args)
                 (setq request-args args)
                 '(:candidates ["猫"]))))
      (should (equal (sekken-server-henkan [(:kind "convert" :text "ねこ")] 3) '("猫"))))
    (should (equal (plist-get (nthcdr 3 request-args) :timeout) 60))
    (should sekken-server--warmed)))

(ert-deftest sekken-server/変換が成功した後は通常のタイムアウトに戻る ()
  (let ((sekken-server--connection 'connection)
        (sekken-server--warmed t)
        (sekken-server-timeout 5)
        (sekken-server-startup-timeout 60)
        request-args)
    (cl-letf (((symbol-function 'sekken-server-connection)
               (lambda () 'connection))
              ((symbol-function 'jsonrpc-request)
               (lambda (&rest args)
                 (setq request-args args)
                 '(:candidates ["猫"]))))
      (sekken-server-henkan [(:kind "convert" :text "ねこ")] 3))
    (should (equal (plist-get (nthcdr 3 request-args) :timeout) 5))))

(ert-deftest sekken-server/接続し直すと起動中に戻る ()
  (let ((sekken-server--connection nil)
        (sekken-server--warmed t))
    (cl-letf (((symbol-function 'make-instance)
               (lambda (&rest _) 'connection))
              ((symbol-function 'jsonrpc-request)
               (lambda (&rest _) (list :version sekken-server-version))))
      (sekken-server--connect))
    (should-not sekken-server--warmed)))

(ert-deftest sekken-server/eventsバッファは短い書式で上限付き ()
  (let ((sekken-server--connection nil)
        config)
    (cl-letf (((symbol-function 'make-instance)
               (lambda (&rest args)
                 (setq config (plist-get (cdr args) :events-buffer-config))
                 'connection))
              ((symbol-function 'jsonrpc-request)
               (lambda (&rest _) (list :version sekken-server-version))))
      (sekken-server--connect))
    (should (eq (plist-get config :format) 'short))
    (should (natnump (plist-get config :size)))))

(ert-deftest sekken-server/接続確認中の失敗は接続を破棄する ()
  (let ((sekken-server--connection nil)
        shutdown)
    (cl-letf (((symbol-function 'make-instance)
               (lambda (&rest _) 'connection))
              ((symbol-function 'jsonrpc-request)
               (lambda (&rest _) (error "interrupted")))
              ((symbol-function 'jsonrpc-shutdown)
               (lambda (conn) (setq shutdown conn))))
      (should-error (sekken-server--connect))
      (should-not sekken-server--connection)
      (should (eq shutdown 'connection)))))

(ert-deftest sekken-server/古い接続の終了で新しい接続を消さない ()
  (let ((sekken-server--connection 'new))
    (sekken-server--on-shutdown 'old)
    (should (eq sekken-server--connection 'new))
    (sekken-server--on-shutdown 'new)
    (should-not sekken-server--connection)))

(ert-deftest sekken-server/非同期の変換は候補を渡し起動中を終える ()
  (let ((sekken-server--connection 'connection)
        (sekken-server--warmed nil)
        (sekken-server--crashes 1)
        (sekken-server-startup-timeout 60)
        request-args
        received)
    (cl-letf (((symbol-function 'sekken-server-connection)
               (lambda () 'connection))
              ((symbol-function 'jsonrpc-async-request)
               (lambda (&rest args)
                 (setq request-args args)
                 (funcall (plist-get (nthcdr 3 args) :success-fn)
                          '(:candidates ["猫" "ねこ"]))
                 '(1))))
      (sekken-server-henkan-async [(:kind "convert" :text "ねこ")] 3
                                  (lambda (candidates) (setq received candidates))))
    (should (equal received '("猫" "ねこ")))
    (should (equal (nth 1 request-args) :henkan))
    (should (equal (nth 2 request-args)
                   '(:pieces [(:kind "convert" :text "ねこ")] :top 3)))
    (should (equal (plist-get (nthcdr 3 request-args) :timeout) 60))
    (should sekken-server--warmed)
    (should (= sekken-server--crashes 0))))

(ert-deftest sekken-server/非同期の変換の失敗はプロセスが死んでいれば異常終了として数える ()
  (let ((sekken-server--connection nil)
        (sekken-server--crashes 0)
        received)
    (cl-letf (((symbol-function 'sekken-server-connection)
               (lambda () (setq sekken-server--connection nil) 'dead))
              ((symbol-function 'jsonrpc-async-request)
               (lambda (&rest args)
                 (funcall (plist-get (nthcdr 3 args) :error-fn)
                          '(:code -32603 :message "internal"))
                 '(1))))
      (sekken-server-henkan-async [(:kind "convert" :text "ねこ")] 3
                                  (lambda (candidates) (setq received candidates))
                                  (lambda () (setq received 'failed))))
    (should (eq received 'failed))
    (should (= sekken-server--crashes 1))))

(ert-deftest sekken-server/非同期の変換の読み込み失敗はプロセスが生きていても異常終了として数える ()
  (let ((sekken-server--connection 'connection)
        (sekken-server--crashes 0))
    (cl-letf (((symbol-function 'sekken-server-connection)
               (lambda () 'connection))
              ((symbol-function 'jsonrpc-running-p)
               (lambda (_) t))
              ((symbol-function 'jsonrpc-async-request)
               (lambda (&rest args)
                 (funcall (plist-get (nthcdr 3 args) :error-fn)
                          (list :code sekken-server--load-failed-code
                                :message "failed to load engine"))
                 '(1))))
      (sekken-server-henkan-async [(:kind "convert" :text "ねこ")] 3 #'ignore))
    (should (= sekken-server--crashes 1))))

(ert-deftest sekken-server/非同期の変換のタイムアウトはプロセスが生きていれば異常終了として数えない ()
  (let ((sekken-server--connection 'connection)
        (sekken-server--crashes 0)
        failed)
    (cl-letf (((symbol-function 'sekken-server-connection)
               (lambda () 'connection))
              ((symbol-function 'jsonrpc-running-p)
               (lambda (_) t))
              ((symbol-function 'jsonrpc-async-request)
               (lambda (&rest args)
                 (funcall (plist-get (nthcdr 3 args) :timeout-fn))
                 '(1))))
      (sekken-server-henkan-async [(:kind "convert" :text "ねこ")] 3 #'ignore
                                  (lambda () (setq failed t))))
    (should failed)
    (should (= sekken-server--crashes 0))))

(provide 'sekken-server-test)
;;; sekken-server-test.el ends here
