;;; sekken-server-test.el --- sekken-server のテスト -*- lexical-binding: t -*-

;; SPDX-License-Identifier: MIT
;;; Code:

(require 'ert)
(require 'sekken-server)

(ert-deftest sekken-server/設定からコマンドラインを組み立てる ()
  (let ((sekken-server-program "/opt/sekken")
        (sekken-server-dic "/d/system.dic.zst")
        (sekken-server-model "/d/model.zst")
        (sekken-server-jisyo "/d/SKK-JISYO.L"))
    (should (equal (sekken-server--command)
                   '("/opt/sekken" "server"
                     "--dic" "/d/system.dic.zst"
                     "--model" "/d/model.zst"
                     "--jisyo" "/d/SKK-JISYO.L")))))

(ert-deftest sekken-server/言語モデルを設定すれば--lmを付ける ()
  (let ((sekken-server-program "/opt/sekken")
        (sekken-server-dic "/d/system.dic.zst")
        (sekken-server-model "/d/model.zst")
        (sekken-server-jisyo "/d/SKK-JISYO.L")
        (sekken-server-lm "/d/lm.zst"))
    (should (equal (sekken-server--command)
                   '("/opt/sekken" "server"
                     "--dic" "/d/system.dic.zst"
                     "--model" "/d/model.zst"
                     "--jisyo" "/d/SKK-JISYO.L"
                     "--lm" "/d/lm.zst")))))

(ert-deftest sekken-server/設定が欠けていればエラーにする ()
  (let ((sekken-server-dic nil))
    (should-error (sekken-server--command) :type 'user-error)))

(ert-deftest sekken-server/プロセスが死んで失敗したら連続異常終了として数える ()
  (require 'cl-lib)
  (let ((sekken-server--connection nil)
        (sekken-server--crashes 0))
    (cl-letf (((symbol-function 'sekken-server-connection)
               (lambda () (setq sekken-server--connection nil) 'dead))
              ((symbol-function 'jsonrpc-request)
               (lambda (&rest _) (signal 'jsonrpc-error '("dead")))))
      (should-error (sekken-server-henkan "Neko" 3))
      (should (= sekken-server--crashes 1)))))

(ert-deftest sekken-server/読み込み失敗の応答はプロセスが生きていても異常終了として数える ()
  (let ((sekken-server--connection 'connection)
        (sekken-server--crashes 0))
    (cl-letf (((symbol-function 'sekken-server-connection)
               (lambda () 'connection))
              ((symbol-function 'jsonrpc-running-p)
               (lambda (_) t))
              ((symbol-function 'jsonrpc-request)
               (lambda (&rest _)
                 (signal 'jsonrpc-error
                         `("request id=1 failed:"
                           (jsonrpc-error-code . ,sekken-server--load-failed-code)
                           (jsonrpc-error-message . "failed to load engine"))))))
      (should-error (sekken-server-henkan "Neko" 3) :type 'jsonrpc-error)
      (should (= sekken-server--crashes 1)))))

(ert-deftest sekken-server/プロセスが生きていればタイムアウトは異常終了として数えない ()
  (let ((sekken-server--connection 'connection)
        (sekken-server--crashes 0))
    (cl-letf (((symbol-function 'sekken-server-connection)
               (lambda () 'connection))
              ((symbol-function 'jsonrpc-running-p)
               (lambda (_) t))
              ((symbol-function 'jsonrpc-request)
               (lambda (&rest _)
                 (signal 'jsonrpc-error
                         '("request id=1 failed:"
                           (jsonrpc-error-message . "Timed out"))))))
      (should-error (sekken-server-henkan "Neko" 3) :type 'jsonrpc-error)
      (should (= sekken-server--crashes 0)))))

(ert-deftest sekken-server/起動中の変換は起動用のタイムアウトで待つ ()
  (let ((sekken-server--connection 'connection)
        (sekken-server--warmed nil)
        (sekken-server-timeout 5)
        (sekken-server-startup-timeout 60)
        request-args)
    (cl-letf (((symbol-function 'sekken-server-connection)
               (lambda () 'connection))
              ((symbol-function 'jsonrpc-request)
               (lambda (&rest args)
                 (setq request-args args)
                 '(:candidates ["猫"]))))
      (should (equal (sekken-server-henkan "Neko" 3) '("猫"))))
    (should (equal (plist-get (nthcdr 3 request-args) :timeout) 60))
    (should sekken-server--warmed)))

(ert-deftest sekken-server/変換が成功した後は通常のタイムアウトに戻る ()
  (let ((sekken-server--connection 'connection)
        (sekken-server--warmed t)
        (sekken-server-timeout 5)
        (sekken-server-startup-timeout 60)
        request-args)
    (cl-letf (((symbol-function 'sekken-server-connection)
               (lambda () 'connection))
              ((symbol-function 'jsonrpc-request)
               (lambda (&rest args)
                 (setq request-args args)
                 '(:candidates ["猫"]))))
      (sekken-server-henkan "Neko" 3))
    (should (equal (plist-get (nthcdr 3 request-args) :timeout) 5))))

(ert-deftest sekken-server/打鍵で取り消しても接続と起動中の扱いは変わらない ()
  (let ((sekken-server--connection 'connection)
        (sekken-server--warmed nil)
        shutdown)
    (cl-letf (((symbol-function 'sekken-server-connection)
               (lambda () 'connection))
              ((symbol-function 'jsonrpc-shutdown)
               (lambda (conn) (setq shutdown conn)))
              ((symbol-function 'jsonrpc-request)
               (lambda (&rest _) sekken-server--input-canceled)))
      (should (eq (sekken-server-henkan "Kana" 1 t)
                  sekken-server--input-canceled)))
    (should (eq sekken-server--connection 'connection))
    (should-not shutdown)
    (should-not sekken-server--warmed)))

(ert-deftest sekken-server/接続し直すと起動中に戻る ()
  (let ((sekken-server--connection nil)
        (sekken-server--warmed t))
    (cl-letf (((symbol-function 'make-instance)
               (lambda (&rest _) 'connection))
              ((symbol-function 'jsonrpc-request)
               (lambda (&rest _) (list :version sekken-server-version))))
      (sekken-server--connect))
    (should-not sekken-server--warmed)))

(ert-deftest sekken-server/先読みは本番と同じ変換要求まで通す ()
  (let (called)
    (cl-letf (((symbol-function 'sekken-server-henkan)
               (lambda (input top &optional cancel-on-input)
                 (setq called (list input top cancel-on-input)))))
      (should (sekken-server--prewarm-attempt)))
    (should (equal called '("Kana" 1 t)))))

(ert-deftest sekken-server/打鍵で中断された先読みは再予約する ()
  (let ((sekken-server--prewarm-timer 'running)
        scheduled)
    (cl-letf (((symbol-function 'sekken-server--configured-p)
               (lambda () t))
              ((symbol-function 'sekken-server--prewarm-attempt)
               (lambda () nil))
              ((symbol-function 'sekken-server-schedule-prewarm)
               (lambda () (setq scheduled t))))
      (sekken-server--run-prewarm))
    (should scheduled)))

(ert-deftest sekken-server/先読みの中断値と完了値を区別する ()
  (cl-letf (((symbol-function 'sekken-server-henkan)
             (lambda (&rest _) sekken-server--input-canceled)))
    (should-not (sekken-server--prewarm-attempt)))
  (cl-letf (((symbol-function 'sekken-server-henkan)
             (lambda (&rest _) '("かな"))))
    (should (sekken-server--prewarm-attempt))))

(ert-deftest sekken-server/先読み要求は打鍵でキャンセルする ()
  (let ((sekken-server--connection 'connection)
        request-args)
    (cl-letf (((symbol-function 'sekken-server-connection)
               (lambda (&optional _) 'connection))
              ((symbol-function 'jsonrpc-request)
               (lambda (&rest args)
                 (setq request-args args)
                 sekken-server--input-canceled)))
      (should (eq (sekken-server-henkan "Kana" 1 t)
                  sekken-server--input-canceled)))
    (should (eq (plist-get (nthcdr 3 request-args) :cancel-on-input) t))
    (should (eq (plist-get (nthcdr 3 request-args) :cancel-on-input-retval)
                sekken-server--input-canceled))))

(ert-deftest sekken-server/接続確認は打鍵で取り消さない ()
  (let ((sekken-server--connection nil)
        request-args)
    (cl-letf (((symbol-function 'make-instance)
               (lambda (&rest _) 'connection))
              ((symbol-function 'jsonrpc-request)
               (lambda (&rest args)
                 (setq request-args args)
                 (list :version sekken-server-version))))
      (should (eq (sekken-server--connect) 'connection)))
    (should (eq sekken-server--connection 'connection))
    (should-not (plist-member (nthcdr 3 request-args) :cancel-on-input))))

(ert-deftest sekken-server/接続確認中の失敗は接続を破棄する ()
  (let ((sekken-server--connection nil)
        shutdown)
    (cl-letf (((symbol-function 'make-instance)
               (lambda (&rest _) 'connection))
              ((symbol-function 'jsonrpc-request)
               (lambda (&rest _) (error "interrupted")))
              ((symbol-function 'jsonrpc-shutdown)
               (lambda (conn) (setq shutdown conn))))
      (should-error (sekken-server--connect))
      (should-not sekken-server--connection)
      (should (eq shutdown 'connection)))))

(ert-deftest sekken-server/古い接続の終了で新しい接続を消さない ()
  (let ((sekken-server--connection 'new))
    (sekken-server--on-shutdown 'old)
    (should (eq sekken-server--connection 'new))
    (sekken-server--on-shutdown 'new)
    (should-not sekken-server--connection)))

(ert-deftest sekken-server/設定前でも先読みを予約できる ()
  (let ((sekken-server--prewarm-timer nil)
        timer-args)
    (cl-letf (((symbol-function 'run-with-idle-timer)
               (lambda (&rest args)
                 (setq timer-args args)
                 'timer)))
      (sekken-server-schedule-prewarm))
    (should (eq sekken-server--prewarm-timer 'timer))
    (should (equal (car timer-args) sekken-server-prewarm-delay))))

(provide 'sekken-server-test)
;;; sekken-server-test.el ends here
